#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE test-db;
    CREATE USER test-user WITH ENCRYPTED PASSWORD test-pwd';
    GRANT ALL PRIVILEGES ON DATABASE test-user TO test-db;
EOSQL
