#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE postgres_keeper;
    CREATE USER keeper WITH ENCRYPTED PASSWORD keeper';
    GRANT ALL PRIVILEGES ON DATABASE keeper TO postgres_keeper;
EOSQL
